name: Client CI

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'client'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: ./client
      - run: npm ci
      - name: Build application
        run: npm run build
      - name: Generate production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_${{ github.sha }}
          path: |
            client/build
            client/firebase.*
            client/.firebaserc
            client/firestore.*
          retention-days: 5
    # - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_${{ github.sha }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Firebase
        run: npm i -g firebase-tools
      - name: Deploy
        run: firebase deploy --only hosting # Cannot deploy firestore.rules here
