# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'
      - run: npm ci
      - name: Build server
        run: npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "server"
          # justlogin: true
      # - run: |
      #     ls
      #     git config --global user.email ${{ secrets.HEROKU_EMAIL }}
      #     git config --global user.name "GitHub Actions"
      #     git add .
      #     git commit -am "Deploy version ${{github.sha}}"
      #     git push heroku main
