# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - run: npm ci
    - name: Build server
      run: npm run build
    - name: Generate production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: server_build_${{ github.sha }}
        path: |
          server/build
        retention-days: 5
    # - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}

    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v3
      with:
        name: server_build_${{ github.sha }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
    - name: Install Heroku CLI
      run: npm install -g heroku
    - run: heroku auth:token
